services:
  leonardo-backend:
    environment:
      # you already had these
      MCP_NETBOX_URL: ${MCP_NETBOX_URL}
      GENAI_API_BASE: ${GENAI_API_BASE}

      # NEW: allow backend to talk directly to NetBox if MCP tool is missing
      NETBOX_DIRECT_BASE: "http://netbox-netbox-1:8080"
      NETBOX_TOKEN: ${NETBOX_TOKEN}
    networks:
      - default
      - genai_local-genai-network
      - netbox_default    # NEW: join NetBox's Docker network so the hostname above resolves

  leonardo-frontend:
    environment:
      # you already had this
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    networks:
      - default
      - genai_local-genai-network

networks:
  genai_local-genai-network:
    external: true
  netbox_default:           # NEW: this is the network created by your NetBox stack
    external: true
