services:
  leonardo-backend:
    build:
      context: .                   # backend needs repo root as context
      dockerfile: backend/Dockerfile
    container_name: leonardo-backend
    env_file:
      - .env
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-0.0.0.0}
      BACKEND_PORT: ${BACKEND_PORT:-10001}
      MCP_NETBOX_URL: ${MCP_NETBOX_URL}
      GENAI_API_BASE: ${GENAI_API_BASE}
    ports:
      - "10001:10001"
    networks:
      - default
      - genai_local-genai-network

  leonardo-frontend:
    build:
      context: ./frontend          # frontend needs its folder as context
      dockerfile: Dockerfile
    container_name: leonardo-frontend
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://localhost:10001}
    depends_on:
      - leonardo-backend
    ports:
      - "10201:80"
    networks:
      - default
      - genai_local-genai-network

networks:
  genai_local-genai-network:
    external: true
