services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: leonardo-backend
    ports:
      - "10001:10001"        # host:container
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILD_ID: ${BUILD_ID}
    container_name: leonardo-frontend
    depends_on:
      - backend
    ports:
      - "10201:10201"
    restart: unless-stopped

