version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: leonardo-backend
    ports:
      - "10001:10001"        # host:container
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: leonardo-frontend
    depends_on:
      - backend
    ports:
      - "80:80"              # app will be at http://<server-ip>/
    restart: unless-stopped
