services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BUILD_ID: ${BUILD_ID}
    ports:
      - "${BACKEND_PORT}:10001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILD_ID: ${BUILD_ID}
    depends_on:
      - backend
    ports:
      target: 80
        published: ${FRONTEND_PORT:-0}
        protocol: tcp
        mode: host
    restart: unless-stopped
