version: "3.9"

services:
  backend:
    image: docker.io/kikulik/leonardo-backend:latest   # public image on Docker Hub
    ports:
      - "10001:10001"
    environment:
      PYTHONUNBUFFERED: "1"
      BUILD_ID: ${BUILD_ID}
    restart: unless-stopped

  frontend:
    image: docker.io/kikulik/leonardo-frontend:latest  # public image on Docker Hub
    depends_on:
      - backend
    ports:
      - "10201:80"
    environment:
      BUILD_ID: ${BUILD_ID}
    restart: unless-stopped
